name: Report generator
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Install md-to-pdf
        run: npm i -g md-to-pdf
        
      - name: Convert md
        run: md-to-pdf "README.md"
        
      - name: Save pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Report for homework
          path: "README.pdf"
          
          
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
        
      - name: Install dependencies
        run: python -m pip install --upgrade pip
        
      - name: Install py-md-to-pdf
        run: git clone https://github.com/chrisconlan/md_math_to_pdf
        
        
      - name: Convert another time
        run: python3 -m ./math_md_to_pdf "README.md"
        
      - name: Save pdf as artifact 2
        uses: actions/upload-artifact@v3
        with:
          name: Report for homework 2
          path: "README.pdf"
      
