name: Report generator
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
    
      - name: Install md2pdf
        run: git clone https://github.com/mandolyte/mdtopdf
        
      - name: Generate pdf
        run: go run ./mdtopdf/cmd/convert.go -i README.md -o "README.pdf"
        
      - name: Save pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Report for homework
          path: "README.pdf"
        
      
