name: Report generator
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Install md2pdf
        run: npm install -g markdown-pdf --ignore-scripts
        
      - name: Generate pdf
        run: markdown-pdf "Report 1.md"
        
      - name: Save pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Report for homework
          path: "Report 1.pdf"
        
      
